### ISSUE TITLE
Packaging ITR_UI.py and data to run from PyPi installation

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [os-climate/ITR-examples#6]
The goal of this issue is to be able to install an environment that allows the user to install ITR-examples from PyPi and run the ITR_UI tool without access to GitHub.

This might involve creating a module that can find the ITR_UI.py script and data from somewhere within site-packages/ITR-examples.  Because we expect the user to be naive, this should work without the user needing to dive into the virtual environment themselves.  The should only need to create the venv, activate it, run a `python -m MODULE` command for some module and then the tool will pop up, possibly publishing the URL of a localhost:port that gives access to the tool in a browser.

Of course if the user has their own data, they should be able to point to that data from the command line, and the tool should open that data instead of the default data supplied with the tool.

@ModeSevenIndustrialSolutions if you can work out the general theory of how to package this, @FannySternfeld and I can chase down the details of actually parsing command lines, etc.

**Comment by ModeSevenIndustrialSolutions** [comment]
We've configured pyproject.toml so that "itr-ui" can be invoked directly from a shell after the ITR-examples package is installed using "pip". Some reworking of the directory structure is required so that bundled data files and example content are available to the tool.

**Comment by ModeSevenIndustrialSolutions** [comment]
The main work on this is now complete. There may be some refactoring of the repository content left to do, and the documentation now needs updating.
